language: python
python: 
 - "3.6.6"
install:
 - pip install -r requirements.txt
sudo: required
services:
 - docker
script:
 - sonar-scanner
 - cd docker
 - docker-compose up -d
 - docker exec -ti decide_web ./manage.py test
 - cd ..
addons:
  sonarcloud:
    organization: "pablotabares-github"
notifications:
  email: false
