language: python
python: 
  - "3.6.6"
env:
  - DJANGO=2.0 DB=postgres
before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
install:
  - pip install -r requirements.txt
before_script:
  - cd decide
  - cp local_settings.travis.py local_settings.py
  - psql -c "create user decide with password 'decide'"
  - psql -c "create database decide owner decide"
  - python manage.py migrate
script:
  - sonar-scanner
  - python manage.py test
  - cd ../docker
  - docker build -t camreyaro/decide .
  - docker tag camreyaro/decide registry.heroku.com/$HEROKU_APP_NAME/web
deploy:
  provider: script
  script: 
    docker push camreyaro/decide;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME;
    heroku config:set WEB_CONCURRENCY=3;
    heroku run --app $HEROKU_APP_NAME python manage.py migrate 
  branch: master
sudo: required
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
  sonarcloud:
    organization: "pablotabares-github"
global:
  - PGPORT=5432
notifications:
  email: false


